# Form implementation generated from reading ui file 'C:\Users\Melina.Shak\Documents\CLAMS_WPy64-31260\CLAMS\ui\AdiposeCondition.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_adiposeCondition(object):
    def setupUi(self, adiposeCondition):
        adiposeCondition.setObjectName("adiposeCondition")
        adiposeCondition.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=adiposeCondition)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 381, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.intact = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intact.sizePolicy().hasHeightForWidth())
        self.intact.setSizePolicy(sizePolicy)
        self.intact.setMinimumSize(QtCore.QSize(165, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.intact.setFont(font)
        self.intact.setObjectName("intact")
        self.verticalLayout.addWidget(self.intact)
        self.clipped = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clipped.sizePolicy().hasHeightForWidth())
        self.clipped.setSizePolicy(sizePolicy)
        self.clipped.setMinimumSize(QtCore.QSize(165, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.clipped.setFont(font)
        self.clipped.setObjectName("clipped")
        self.verticalLayout.addWidget(self.clipped)

        self.retranslateUi(adiposeCondition)
        QtCore.QMetaObject.connectSlotsByName(adiposeCondition)

    def retranslateUi(self, adiposeCondition):
        _translate = QtCore.QCoreApplication.translate
        adiposeCondition.setWindowTitle(_translate("adiposeCondition", "Dialog"))
        self.label.setText(_translate("adiposeCondition", "Adipose fin condition: "))
        self.intact.setText(_translate("adiposeCondition", "Clipped"))
        self.clipped.setText(_translate("adiposeCondition", "Intact"))
