# Form implementation generated from reading ui file 'DuplicateDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_YesNoDlg(object):
    def setupUi(self, YesNoDlg):
        YesNoDlg.setObjectName("YesNoDlg")
        YesNoDlg.resize(596, 222)
        YesNoDlg.setMinimumSize(QtCore.QSize(354, 180))
        YesNoDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(YesNoDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.msgLabel = QtWidgets.QLabel(YesNoDlg)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.msgLabel.setFont(font)
        self.msgLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.msgLabel.setObjectName("msgLabel")
        self.verticalLayout.addWidget(self.msgLabel)
        self.yesBtn = QtWidgets.QPushButton(YesNoDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yesBtn.sizePolicy().hasHeightForWidth())
        self.yesBtn.setSizePolicy(sizePolicy)
        self.yesBtn.setMinimumSize(QtCore.QSize(165, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.yesBtn.setFont(font)
        self.yesBtn.setObjectName("yesBtn")
        self.verticalLayout.addWidget(self.yesBtn)
        self.noBtn = QtWidgets.QPushButton(YesNoDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noBtn.sizePolicy().hasHeightForWidth())
        self.noBtn.setSizePolicy(sizePolicy)
        self.noBtn.setMinimumSize(QtCore.QSize(168, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.noBtn.setFont(font)
        self.noBtn.setObjectName("noBtn")
        self.verticalLayout.addWidget(self.noBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(YesNoDlg)
        QtCore.QMetaObject.connectSlotsByName(YesNoDlg)

    def retranslateUi(self, YesNoDlg):
        _translate = QtCore.QCoreApplication.translate
        YesNoDlg.setWindowTitle(_translate("YesNoDlg", "Yes or No?"))
        self.msgLabel.setText(_translate("YesNoDlg", "You have already pressed this button.\n"
"Would you like to overwrite the previous?"))
        self.yesBtn.setText(_translate("YesNoDlg", "Yes"))
        self.noBtn.setText(_translate("YesNoDlg", "No"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    YesNoDlg = QtWidgets.QDialog()
    ui = Ui_YesNoDlg()
    ui.setupUi(YesNoDlg)
    YesNoDlg.show()
    sys.exit(app.exec())
