# Form implementation generated from reading ui file 'EditPersonnelDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditPersonnelDlg(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(407, 251)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.addPersonBtn = QtWidgets.QPushButton(parent=Dialog)
        self.addPersonBtn.setGeometry(QtCore.QRect(210, 190, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.addPersonBtn.setFont(font)
        self.addPersonBtn.setObjectName("addPersonBtn")
        self.scientistLabel = QtWidgets.QLineEdit(parent=Dialog)
        self.scientistLabel.setGeometry(QtCore.QRect(150, 20, 241, 41))
        self.scientistLabel.setObjectName("scientistLabel")
        self.affiliationLabel = QtWidgets.QLineEdit(parent=Dialog)
        self.affiliationLabel.setGeometry(QtCore.QRect(150, 70, 241, 41))
        self.affiliationLabel.setObjectName("affiliationLabel")
        self.isActive = QtWidgets.QCheckBox(parent=Dialog)
        self.isActive.setGeometry(QtCore.QRect(150, 140, 75, 20))
        self.isActive.setText("")
        self.isActive.setObjectName("isActive")
        self.cancelBtn = QtWidgets.QPushButton(parent=Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(90, 190, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Scientist"))
        self.label_2.setText(_translate("Dialog", "Affiliation"))
        self.label_3.setText(_translate("Dialog", "Active"))
        self.addPersonBtn.setText(_translate("Dialog", "Add Personnel"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
