# Form implementation generated from reading ui file 'FEATGonadDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(238, 347)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pb_take_nad = QtWidgets.QPushButton(Dialog)
        self.pb_take_nad.setMinimumSize(QtCore.QSize(220, 50))
        self.pb_take_nad.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_take_nad.setFont(font)
        self.pb_take_nad.setObjectName("pb_take_nad")
        self.verticalLayout.addWidget(self.pb_take_nad)
        self.pb_nad_wt = QtWidgets.QPushButton(Dialog)
        self.pb_nad_wt.setMinimumSize(QtCore.QSize(220, 50))
        self.pb_nad_wt.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_nad_wt.setFont(font)
        self.pb_nad_wt.setObjectName("pb_nad_wt")
        self.verticalLayout.addWidget(self.pb_nad_wt)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setStyleSheet("font: 12pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.l_cur_code = QtWidgets.QLabel(Dialog)
        self.l_cur_code.setStyleSheet("font: 12pt \"Arial Black\";")
        self.l_cur_code.setObjectName("l_cur_code")
        self.verticalLayout.addWidget(self.l_cur_code)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_cancel = QtWidgets.QPushButton(Dialog)
        self.pb_cancel.setMinimumSize(QtCore.QSize(100, 50))
        self.pb_cancel.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_cancel.setFont(font)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout.addWidget(self.pb_cancel)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_done = QtWidgets.QPushButton(Dialog)
        self.pb_done.setMinimumSize(QtCore.QSize(100, 50))
        self.pb_done.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_done.setFont(font)
        self.pb_done.setObjectName("pb_done")
        self.horizontalLayout.addWidget(self.pb_done)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Gonads"))
        self.label.setText(_translate("Dialog", "Gonad Collection"))
        self.pb_take_nad.setText(_translate("Dialog", "Take Gonad"))
        self.pb_nad_wt.setText(_translate("Dialog", "Gonad Weight"))
        self.label_4.setText(_translate("Dialog", "Current Barcode"))
        self.l_cur_code.setText(_translate("Dialog", "None"))
        self.pb_cancel.setText(_translate("Dialog", "Cancel"))
        self.pb_done.setText(_translate("Dialog", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
