# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\noaa-afsc-mace\CLAMS\ui\FEATTrawlEvent.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(671, 668)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\rick.towler\\Work\\noaa-afsc-mace\\CLAMS\\ui\\../../icons/giant_clam.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.l_current = QtWidgets.QLabel(parent=Dialog)
        self.l_current.setGeometry(QtCore.QRect(20, 90, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.l_current.setFont(font)
        self.l_current.setObjectName("l_current")
        self.pb_cancel = QtWidgets.QPushButton(parent=Dialog)
        self.pb_cancel.setGeometry(QtCore.QRect(410, 560, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb_cancel.setFont(font)
        self.pb_cancel.setObjectName("pb_cancel")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(240, 280, 231, 261))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pb_choose = QtWidgets.QPushButton(parent=self.frame)
        self.pb_choose.setGeometry(QtCore.QRect(10, 20, 211, 51))
        self.pb_choose.setObjectName("pb_choose")
        self.pb_add = QtWidgets.QPushButton(parent=self.frame)
        self.pb_add.setGeometry(QtCore.QRect(10, 80, 211, 51))
        self.pb_add.setObjectName("pb_add")
        self.pb_edit = QtWidgets.QPushButton(parent=self.frame)
        self.pb_edit.setGeometry(QtCore.QRect(10, 140, 211, 51))
        self.pb_edit.setObjectName("pb_edit")
        self.pb_connect = QtWidgets.QPushButton(parent=self.frame)
        self.pb_connect.setGeometry(QtCore.QRect(10, 200, 211, 51))
        self.pb_connect.setObjectName("pb_connect")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lw_events = QtWidgets.QListWidget(parent=Dialog)
        self.lw_events.setGeometry(QtCore.QRect(40, 210, 191, 391))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lw_events.setFont(font)
        self.lw_events.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.lw_events.setObjectName("lw_events")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(470, 280, 181, 261))
        self.textBrowser.setObjectName("textBrowser")
        self.cb_active = QtWidgets.QCheckBox(parent=Dialog)
        self.cb_active.setGeometry(QtCore.QRect(220, 170, 171, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_active.setFont(font)
        self.cb_active.setChecked(True)
        self.cb_active.setObjectName("cb_active")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CLAMS Haul"))
        self.l_current.setText(_translate("Dialog", "Current Event: "))
        self.pb_cancel.setText(_translate("Dialog", "Cancel"))
        self.pb_choose.setText(_translate("Dialog", "Choose Event"))
        self.pb_add.setText(_translate("Dialog", "Add Event"))
        self.pb_edit.setText(_translate("Dialog", "Edit Event Number"))
        self.pb_connect.setText(_translate("Dialog", "Connect Event"))
        self.label_2.setText(_translate("Dialog", "Events in Database"))
        self.label_3.setText(_translate("Dialog", "Select FEAT Trawl Event"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Select</span><span style=\" font-size:8pt;\"> an event from the list to change it to the active event and move on.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Add</span><span style=\" font-size:8pt;\"> an event if the net config app HAS NOT been uploaded to the final database. - </span><span style=\" font-size:8pt; font-style:italic;\">This is the most common</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Edit</span><span style=\" font-size:8pt;\"> and event number - if there are no samples associated with an event, you may change the event number here. If you need to edit an event number that HAS samples, contact the administrator</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Connect</span><span style=\" font-size:8pt;\"> an event if the net config app HAS been uploaded to the final database.</span></p></body></html>"))
        self.cb_active.setText(_translate("Dialog", "Show Active Only"))
