# Form implementation generated from reading ui file 'C:\Users\Melina.Shak\Documents\CLAMS\ui\MatSelDlgABL.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_matselDlgABL(object):
    def setupUi(self, matselDlgABL):
        matselDlgABL.setObjectName("matselDlgABL")
        matselDlgABL.resize(271, 148)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(matselDlgABL)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=matselDlgABL)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.immatureBtn = QtWidgets.QPushButton(parent=matselDlgABL)
        self.immatureBtn.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.immatureBtn.setFont(font)
        self.immatureBtn.setObjectName("immatureBtn")
        self.verticalLayout.addWidget(self.immatureBtn)
        self.maturingBtn = QtWidgets.QPushButton(parent=matselDlgABL)
        self.maturingBtn.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.maturingBtn.setFont(font)
        self.maturingBtn.setObjectName("maturingBtn")
        self.verticalLayout.addWidget(self.maturingBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(matselDlgABL)
        QtCore.QMetaObject.connectSlotsByName(matselDlgABL)

    def retranslateUi(self, matselDlgABL):
        _translate = QtCore.QCoreApplication.translate
        matselDlgABL.setWindowTitle(_translate("matselDlgABL", "Maturity Selection"))
        self.label.setText(_translate("matselDlgABL", "Select the maturity..."))
        self.immatureBtn.setText(_translate("matselDlgABL", "Immature"))
        self.maturingBtn.setText(_translate("matselDlgABL", "Maturing"))
