# Form implementation generated from reading ui file 'C:\Users\Melina.Shak\Documents\CLAMS_WPy64-31260\CLAMS\ui\NetDlg_CPS.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_netDlg(object):
    def setupUi(self, netDlg):
        netDlg.setObjectName("netDlg")
        netDlg.resize(662, 294)
        self.verticalLayout = QtWidgets.QVBoxLayout(netDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cancelBtn = QtWidgets.QPushButton(parent=netDlg)
        self.cancelBtn.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.gridLayout_3.addWidget(self.cancelBtn, 4, 2, 1, 1)
        self.pb_door_spread = QtWidgets.QPushButton(parent=netDlg)
        self.pb_door_spread.setMinimumSize(QtCore.QSize(250, 40))
        self.pb_door_spread.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pb_door_spread.setFont(font)
        self.pb_door_spread.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"}")
        self.pb_door_spread.setText("")
        self.pb_door_spread.setFlat(False)
        self.pb_door_spread.setObjectName("pb_door_spread")
        self.gridLayout_3.addWidget(self.pb_door_spread, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(parent=netDlg)
        self.label_4.setMinimumSize(QtCore.QSize(300, 0))
        self.label_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.pb_fr = QtWidgets.QPushButton(parent=netDlg)
        self.pb_fr.setMinimumSize(QtCore.QSize(250, 40))
        self.pb_fr.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pb_fr.setFont(font)
        self.pb_fr.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"}")
        self.pb_fr.setText("")
        self.pb_fr.setObjectName("pb_fr")
        self.gridLayout_3.addWidget(self.pb_fr, 1, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(parent=netDlg)
        self.label_5.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.saveButton = QtWidgets.QPushButton(parent=netDlg)
        self.saveButton.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_3.addWidget(self.saveButton, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)

        self.retranslateUi(netDlg)
        QtCore.QMetaObject.connectSlotsByName(netDlg)

    def retranslateUi(self, netDlg):
        _translate = QtCore.QCoreApplication.translate
        netDlg.setWindowTitle(_translate("netDlg", "Net Mensuration Dialog"))
        self.cancelBtn.setText(_translate("netDlg", "Cancel"))
        self.label_4.setText(_translate("netDlg", "Door Spread"))
        self.label_5.setText(_translate("netDlg", "FR"))
        self.saveButton.setText(_translate("netDlg", "Save"))
