# Form implementation generated from reading ui file 'PersonnelDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PersonnelDlg(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(608, 648)
        self.editBtn = QtWidgets.QPushButton(parent=Dialog)
        self.editBtn.setGeometry(QtCore.QRect(230, 590, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.editBtn.setFont(font)
        self.editBtn.setObjectName("editBtn")
        self.doneBtn = QtWidgets.QPushButton(parent=Dialog)
        self.doneBtn.setGeometry(QtCore.QRect(370, 590, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName("doneBtn")
        self.addBtn = QtWidgets.QPushButton(parent=Dialog)
        self.addBtn.setGeometry(QtCore.QRect(90, 590, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName("addBtn")
        self.personnelTable = QtWidgets.QTableWidget(parent=Dialog)
        self.personnelTable.setGeometry(QtCore.QRect(30, 20, 551, 561))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        self.personnelTable.setFont(font)
        self.personnelTable.setObjectName("personnelTable")
        self.personnelTable.setColumnCount(3)
        self.personnelTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.personnelTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.personnelTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.personnelTable.setHorizontalHeaderItem(2, item)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.editBtn.setText(_translate("Dialog", "Edit"))
        self.doneBtn.setText(_translate("Dialog", "Done"))
        self.addBtn.setText(_translate("Dialog", "Add"))
        item = self.personnelTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Scientist"))
        item = self.personnelTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Affiliation"))
        item = self.personnelTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Active"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
