# Form implementation generated from reading ui file 'C:\Users\Melina.Shak\Documents\CLAMS_WPy64-31260\CLAMS\ui\QSCSTestPollCompare.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QSCSTestPollCompare(object):
    def setupUi(self, QSCSTestPollCompare):
        QSCSTestPollCompare.setObjectName("QSCSTestPollCompare")
        QSCSTestPollCompare.resize(486, 312)
        self.centralwidget = QtWidgets.QWidget(parent=QSCSTestPollCompare)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.compareButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.compareButton.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.compareButton.setFont(font)
        self.compareButton.setObjectName("compareButton")
        self.verticalLayout_3.addWidget(self.compareButton)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.scsText = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.scsText.setMaximumSize(QtCore.QSize(10000, 10000))
        self.scsText.setObjectName("scsText")
        self.verticalLayout_3.addWidget(self.scsText)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        QSCSTestPollCompare.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=QSCSTestPollCompare)
        self.statusbar.setObjectName("statusbar")
        QSCSTestPollCompare.setStatusBar(self.statusbar)

        self.retranslateUi(QSCSTestPollCompare)
        QtCore.QMetaObject.connectSlotsByName(QSCSTestPollCompare)

    def retranslateUi(self, QSCSTestPollCompare):
        _translate = QtCore.QCoreApplication.translate
        QSCSTestPollCompare.setWindowTitle(_translate("QSCSTestPollCompare", "pyQt SCS Client Tester"))
        self.compareButton.setText(_translate("QSCSTestPollCompare", "Compare"))
        self.label_2.setText(_translate("QSCSTestPollCompare", "Sensors from database compared to SCS stream"))
