# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\noaa-afsc-mace\CLAMS\ui\SWFSCFinClipDNADlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SWFSCFinClipDNADlg(object):
    def setupUi(self, SWFSCFinClipDNADlg):
        SWFSCFinClipDNADlg.setObjectName("SWFSCFinClipDNADlg")
        SWFSCFinClipDNADlg.resize(485, 188)
        SWFSCFinClipDNADlg.setMinimumSize(QtCore.QSize(354, 180))
        SWFSCFinClipDNADlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(SWFSCFinClipDNADlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.msgLabel = QtWidgets.QLabel(parent=SWFSCFinClipDNADlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.msgLabel.setFont(font)
        self.msgLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.msgLabel.setObjectName("msgLabel")
        self.verticalLayout.addWidget(self.msgLabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.yesBtn = QtWidgets.QPushButton(parent=SWFSCFinClipDNADlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yesBtn.sizePolicy().hasHeightForWidth())
        self.yesBtn.setSizePolicy(sizePolicy)
        self.yesBtn.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yesBtn.setFont(font)
        self.yesBtn.setObjectName("yesBtn")
        self.gridLayout.addWidget(self.yesBtn, 0, 0, 1, 1)
        self.noBtn = QtWidgets.QPushButton(parent=SWFSCFinClipDNADlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noBtn.sizePolicy().hasHeightForWidth())
        self.noBtn.setSizePolicy(sizePolicy)
        self.noBtn.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.noBtn.setFont(font)
        self.noBtn.setObjectName("noBtn")
        self.gridLayout.addWidget(self.noBtn, 1, 0, 1, 1)
        self.vialNumberBtn = QtWidgets.QPushButton(parent=SWFSCFinClipDNADlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.vialNumberBtn.setFont(font)
        self.vialNumberBtn.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"}")
        self.vialNumberBtn.setObjectName("vialNumberBtn")
        self.gridLayout.addWidget(self.vialNumberBtn, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 70)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(SWFSCFinClipDNADlg)
        QtCore.QMetaObject.connectSlotsByName(SWFSCFinClipDNADlg)

    def retranslateUi(self, SWFSCFinClipDNADlg):
        _translate = QtCore.QCoreApplication.translate
        SWFSCFinClipDNADlg.setWindowTitle(_translate("SWFSCFinClipDNADlg", "DNA Finclip?"))
        self.msgLabel.setText(_translate("SWFSCFinClipDNADlg", "Are you taking a DNA Fin Clip?"))
        self.yesBtn.setText(_translate("SWFSCFinClipDNADlg", "Yes"))
        self.noBtn.setText(_translate("SWFSCFinClipDNADlg", "No"))
        self.vialNumberBtn.setText(_translate("SWFSCFinClipDNADlg", "YYSSVVXXX"))
