# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\noaa-afsc-mace\CLAMS\ui\SWFSCFinClipDNA.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SWFSCFinClipDNA(object):
    def setupUi(self, SWFSCFinClipDNA):
        SWFSCFinClipDNA.setObjectName("SWFSCFinClipDNA")
        SWFSCFinClipDNA.resize(533, 204)
        SWFSCFinClipDNA.setMinimumSize(QtCore.QSize(354, 180))
        SWFSCFinClipDNA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(SWFSCFinClipDNA)
        self.verticalLayout.setObjectName("verticalLayout")
        self.msgLabel = QtWidgets.QLabel(parent=SWFSCFinClipDNA)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.msgLabel.setFont(font)
        self.msgLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.msgLabel.setObjectName("msgLabel")
        self.verticalLayout.addWidget(self.msgLabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.yesBtn = QtWidgets.QPushButton(parent=SWFSCFinClipDNA)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yesBtn.sizePolicy().hasHeightForWidth())
        self.yesBtn.setSizePolicy(sizePolicy)
        self.yesBtn.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yesBtn.setFont(font)
        self.yesBtn.setObjectName("yesBtn")
        self.gridLayout.addWidget(self.yesBtn, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=SWFSCFinClipDNA)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.noBtn = QtWidgets.QPushButton(parent=SWFSCFinClipDNA)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noBtn.sizePolicy().hasHeightForWidth())
        self.noBtn.setSizePolicy(sizePolicy)
        self.noBtn.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.noBtn.setFont(font)
        self.noBtn.setObjectName("noBtn")
        self.gridLayout.addWidget(self.noBtn, 1, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 70)
        self.gridLayout.setColumnStretch(1, 30)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(SWFSCFinClipDNA)
        QtCore.QMetaObject.connectSlotsByName(SWFSCFinClipDNA)

    def retranslateUi(self, SWFSCFinClipDNA):
        _translate = QtCore.QCoreApplication.translate
        SWFSCFinClipDNA.setWindowTitle(_translate("SWFSCFinClipDNA", "DNA Finclip?"))
        self.msgLabel.setText(_translate("SWFSCFinClipDNA", "Are you taking a DNA Fin Clip?"))
        self.yesBtn.setText(_translate("SWFSCFinClipDNA", "Yes"))
        self.lineEdit.setText(_translate("SWFSCFinClipDNA", "YYSSVVXXX"))
        self.noBtn.setText(_translate("SWFSCFinClipDNA", "No"))
