# Form implementation generated from reading ui file 'ScaleCardDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_scalecardDlg(object):
    def setupUi(self, scalecardDlg):
        scalecardDlg.setObjectName("scalecardDlg")
        scalecardDlg.resize(287, 320)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(scalecardDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(scalecardDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(scalecardDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cardBtn = QtWidgets.QPushButton(scalecardDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardBtn.sizePolicy().hasHeightForWidth())
        self.cardBtn.setSizePolicy(sizePolicy)
        self.cardBtn.setMinimumSize(QtCore.QSize(165, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cardBtn.setFont(font)
        self.cardBtn.setObjectName("cardBtn")
        self.verticalLayout.addWidget(self.cardBtn)
        self.label_2 = QtWidgets.QLabel(scalecardDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.positionBtn = QtWidgets.QPushButton(scalecardDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positionBtn.sizePolicy().hasHeightForWidth())
        self.positionBtn.setSizePolicy(sizePolicy)
        self.positionBtn.setMinimumSize(QtCore.QSize(165, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.positionBtn.setFont(font)
        self.positionBtn.setObjectName("positionBtn")
        self.verticalLayout.addWidget(self.positionBtn)
        self.doneBtn = QtWidgets.QPushButton(scalecardDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doneBtn.sizePolicy().hasHeightForWidth())
        self.doneBtn.setSizePolicy(sizePolicy)
        self.doneBtn.setMinimumSize(QtCore.QSize(165, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName("doneBtn")
        self.verticalLayout.addWidget(self.doneBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(scalecardDlg)
        QtCore.QMetaObject.connectSlotsByName(scalecardDlg)

    def retranslateUi(self, scalecardDlg):
        _translate = QtCore.QCoreApplication.translate
        scalecardDlg.setWindowTitle(_translate("scalecardDlg", "Scale Location"))
        self.label_3.setText(_translate("scalecardDlg", "Fish Scale Location"))
        self.label.setText(_translate("scalecardDlg", "Card Number"))
        self.cardBtn.setText(_translate("scalecardDlg", "enter"))
        self.label_2.setText(_translate("scalecardDlg", "Card Position"))
        self.positionBtn.setText(_translate("scalecardDlg", "enter"))
        self.doneBtn.setText(_translate("scalecardDlg", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    scalecardDlg = QtWidgets.QDialog()
    ui = Ui_scalecardDlg()
    ui.setupUi(scalecardDlg)
    scalecardDlg.show()
    sys.exit(app.exec())
