# Form implementation generated from reading ui file 'WorkstationDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WorkstationDlg(object):
    def setupUi(self, WorkstationDlg):
        WorkstationDlg.setObjectName("WorkstationDlg")
        WorkstationDlg.resize(552, 640)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=WorkstationDlg)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 511, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.workstationTable = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        self.workstationTable.setFont(font)
        self.workstationTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.workstationTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.workstationTable.setObjectName("workstationTable")
        self.workstationTable.setColumnCount(3)
        self.workstationTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.workstationTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.workstationTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.workstationTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.workstationTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName("addBtn")
        self.horizontalLayout.addWidget(self.addBtn)
        self.editBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.editBtn.setFont(font)
        self.editBtn.setObjectName("editBtn")
        self.horizontalLayout.addWidget(self.editBtn)
        self.doneBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName("doneBtn")
        self.horizontalLayout.addWidget(self.doneBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(WorkstationDlg)
        QtCore.QMetaObject.connectSlotsByName(WorkstationDlg)

    def retranslateUi(self, WorkstationDlg):
        _translate = QtCore.QCoreApplication.translate
        WorkstationDlg.setWindowTitle(_translate("WorkstationDlg", "Dialog"))
        item = self.workstationTable.horizontalHeaderItem(0)
        item.setText(_translate("WorkstationDlg", "Id"))
        item = self.workstationTable.horizontalHeaderItem(1)
        item.setText(_translate("WorkstationDlg", "Hostname"))
        item = self.workstationTable.horizontalHeaderItem(2)
        item.setText(_translate("WorkstationDlg", "Description"))
        self.addBtn.setText(_translate("WorkstationDlg", "Add"))
        self.editBtn.setText(_translate("WorkstationDlg", "Edit"))
        self.doneBtn.setText(_translate("WorkstationDlg", "Done"))
